### PR TITLE
Arima doc

### PR DESCRIPTION
**Pull request by mbsabath**
The `setx` and `setx1` methods both need to be called in order to successfully plot the results of time series models. Previously this was not documented. I added a line to the Arima vignette so this would be clear.

### CODE REVIEW

**Comment by christophergandrud** [comment]
Thanks @mbsabath 

Can you split off https://github.com/IQSS/Zelig/pull/298/commits/301a2547460b79d3130356a6357b01e64003147c
and make a pull request with just this?

The `setx` issue I think needs more work, discussed over at https://github.com/IQSS/Zelig/issues/299

**Comment by mbsabath** [comment]
I can do that, although this branch consists only of documentation changes to this file, so my thoughts on the matter are that it would make sense to merge both of these changes in at once, rather than separately.

**Comment by christophergandrud** [comment]
My thinking is that we don't really need to hold up the deployment of one document change while we solve an unrelated bug. (I'ld rather not create documentation for a bug, but solve the bug.)

**Comment by mbsabath** [comment]
Reasonable, I thought you wanted to hold off on updating the arima doc with the general information in the first commit until the bug was fixed.

**Pull request closed without merging**
