### PR TITLE
changes to pass CRAN tests

### PR DESCRIPTION
**Pull request by tercer**
Removed tests flagged by @cchoirat .  
Removed ZeligChoice, ZeligEI, zeligverse dependencies for present.  
Bumped version number.

### CODE REVIEW

**Comment by tercer** [comment]
Note, needs new maintainer.

**Comment by rtreacy** [comment]
Is changing the maintainer just a matter of changing the name in the DESCRIPTION file? I can be the maintainer

**Review by rtreacy — APPROVED** [review]
The removal of the ZeligChoice, ZeligEI and zeligverse dependencies are what I had in mind, along with the removal of library(zeligverse) for now

**Review by rtreacy — COMMENTED** [review]
meant to just comment on changing DESCRIPTION to remove ZeligChoice, ZeligEI and zeligverse dependencies and remove library(zeligverse) in testthat.R.
Also I can be the maintainer if that's ok with everyone

**Pull request merged**
